services:
  database:
    container_name: database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: caller
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - mysql:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
  php:
    container_name: php
    build:
      context: php
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/app
      - vendor:/var/lib/vendor:cached
      - var:/var/lib/var:cached
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
volumes:
  mysql:
  vendor:
  var:
