services:
  postgres_db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: caller
    ports:
      - '5431:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
  php:
    container_name: php
    build:
      context: php
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/app
      - vendor:/var/lib/vendor:cached
      - var:/var/lib/var:cached
    depends_on:
      - postgres_db
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres_db
volumes:
  postgres-data:
  vendor:
  var:
